api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path("todo/list/", views.ApiTodoLV.as_view(), name="list"),
    path("todo/<int:pk>/delete/", views.ApiTodoDelV.as_view(), name="delete"),
    path("todo/create/", views.ApiTodoCV.as_view(), name="create"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path("api/", include('api.urls')),
]

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.TodoTV.as_view(), name="index")
]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo
    
    def save(self, force_insert=False, forece_updatge=False, using=None, update_fields=None):
        if not self.name:
            self.name = '홍길동'
        super().save() # 상위(슈퍼) 클래스의 save 메소드 호출 ==> 실제로 저장이 완료된다.

api/views.py
import json

from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.views.generic import DeleteView, ListView
from django.views.generic.edit import BaseCreateView, BaseDeleteView
from django.views.generic.list import BaseListView

from todo.models import Todo


# ensure_csrf_cookie 데코레이터는
# cookie에 csrf Token을 담아서 클라이언트게 전해준다. (클라이언트의 첫 진입 시점에 발급)
# 보통의 경우 '{% csrf_token %}'을 사용하면 django에서 위 과정을 알아서 처리해준다.
# 하지만 본 예제의 경우, csrf_token 탬플릿 태그를 사용하지 않기 때문에
# 이와 같은 데코레이터 기능이 필요한 것이다.
@method_decorator(ensure_csrf_cookie, name='dispatch')
class ApiTodoLV(BaseListView):
    model = Todo

    def render_to_response(self, context, **response_kwargs):
        # values 메소드는 테이블에서 가져온 각각의 레코드들을 딕셔너리로 풀어준다
        todoList = list(context['object_list'].values())
        return JsonResponse(data=todoList, safe=False, status=200)


# csrf 임시로 꺼놓기
# 클래스에 데코레이터 설정하기
# @method_decorator(csrf_exempt, name='dispatch')
class ApiTodoDelV(BaseDeleteView):
    model = Todo
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return JsonResponse(data={}, status=204)


# @method_decorator(csrf_exempt, name='dispatch')
class ApiTodoCV(BaseCreateView):
    model = Todo
    fields = '__all__' # createview는 내부에서 form을 만들기 때문에 fields 속성은 필수

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # form 형식으로 받을 때는 request.POST
        # form 형식이 아닌 경우에는 request.body
        # 그런데 request.body는 Json(str) 형태이기 때문에 이를 딕셔너리로 바꿔줄 수 있는 json 모듈을 사용해야 한다.
        kwargs['data'] = json.loads(self.request.body) 
        return kwargs


    def form_valid(self, form):
        print('form_valid()', form)
        self.object = form.save()
        newTodo = model_to_dict(self.object) # self.object가 모델 타입이기 때문에 딕셔너리로 변환
        print(f'newTodo: {newTodo}')
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        print('form_invalid()', form)
        # form.errors의 데이터 타입은 딕셔너리!
        return JsonResponse(data=form.errors, status=400)


"""
BaseDeleteView와 DeleteView의 차이
(ListView도 마찬가지)

DeleteView는 template 처리에 대한 로직도 포함되어 있다.
하지만 현재 로직에서는 JsonResponse로 응답을 하기 때문에
template 처리는 필요없는 기능이다.
그러므로 BaseDeleteView를 사용하는 것이 좀 더 간결한 코드라고 할 수 있다.

"""

# class ApiTodoLV(ListView):
#     model = Todo

#     # def get(self, request, *args, **kwargs):
#     #     tmpList = [
#     #         {'id': 1, 'name': 'd박정빈', 'todo': '풋살하기'},
#     #         {'id': 2, 'name': 'd박정빈', 'todo': '인프런 강의듣기'},
#     #         {'id': 3, 'name': 'd홍길동', 'todo': '장작패기'},
#     #         {'id': 4, 'name': 'd홍길동', 'todo': '순찰돌기'},
#     #     ]
#     #     return JsonResponse(data=tmpList, safe=False)

#     def render_to_response(self, context, **response_kwargs):
#         # values 메소드는 테이블에서 가져온 각각의 레코드들을 딕셔너리로 풀어준다
#         todoList = list(context['object_list'].values())
#         return JsonResponse(data=todoList, safe=False, status=200)


# # csrf 임시로 꺼놓기
# # 클래스에 데코레이터 설정하기
# @method_decorator(csrf_exempt, name='dispatch')
# class ApiTodoDelV(DeleteView):
#     model = Todo
    
#     def delete(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         self.object.delete()

#         return JsonResponse(data={}, status=204)

config/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

todo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class TodoTV(TemplateView):
    template_name = "todo/todo_index.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}home.html
    {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}
    {% endblock extra-style %}
</head>
<body style="padding-top:90px;">

<!-- 메인 메뉴 -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item mx-1 btn btn-dark ">
                    <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn btn-dark ">
                    <a class="nav-link text-white" href="{% url 'todo:index' %}">Todo</a>
                </li>
                <li class="nav-item mx-1 btn btn-dark ">
                    <a class="nav-link text-white" href="{% url 'home' %}">Blog(tobe)</a>
                </li>
                
                <li class="nav-item mx-1 btn btn-dark ">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Until</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'admin:index' %}" class="dropdown-item">Admin</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>

            <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
            </form>

            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-dark">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;
                    </a>
                    <div class="dropdown-menu">
                        <a href="{% url 'home' %}" class="dropdown-item">Login</a>
                        <a href="{% url 'home' %}" class="dropdown-item">Register</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    {% block footer %}
    {% endblock footer %}

    <script src="https://kit.fontawesome.com/0cf4c20639.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block extra-script %}
    {% endblock extra-script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">

    .home-window {

        background-image: url("{% static 'img/sleeping.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        height: 50vh;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        color: yellow;
        padding: 20px 0 0 20px;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }

    .footer-wrapper {
        background: #456;
        color: #eee;
        line-height: 50px;
    }
    .footer-wrapper a {
        color: #ff9;    /* footer-right text */
    }
    .footer-wrapper a:hover {
        color: #0ff;
    }
    footer ul li {
        text-align: center;
    }

</style>
{% endblock extra-style %}

{% block content %}
    <div class="home-window">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-cog"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Todo App</h3>
            <p>With Todo app, you can manage, prioritize, and complete the most important things
                you need to do every day. I can focus on the most important things
                and I can do my day more deliberately.
                You can also share lists with colleagues, friends, and family.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p>Copyright &copy; 2019 DjangoBook by shkim</p>
            </div>
            <div class="col-md-8">
                <ul class="list-inline float-right">
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Introduction</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Help</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Policy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Something</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock footer %}

{% block extra-script %}
<script>
$(function () {
    $('[data-toggle=tooltip]').tooltip();
});
</script>
{% endblock extra-script %}

todo/templates/todo/todo_index.html
{% extends 'base.html' %}

{% block title %}
Vue.js - Django todo app
{% endblock title %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;

        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
            background: none;
        }

        .removeBtn:hover {
            color: red;
        }
        button {
            cursor: pointer;
            border: 0;
            outline: 0;
        }
    </style>
{% endblock extra-style %}


{% block content %}
    <div id='app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>

        <!-- vue를 통해서 서버에 요청할 것이기 때문에 form 형식을 사용할 필요가 없다.-->
        <div class="inputBox">
            <input class="name" type="text" placeholder="name ..." v-model.trim="name">
            <input class="item" type="text" placeholder="type anything welcomed ..." v-model.trim="todo" v-on:keyup.enter='add_todo()'>
            <button class=" btn btn-primary btn-sm" type="button" v-on:click="add_todo()">ADD</button>
        </div>

        <ul class="todoList">
            <li v-for ='(todo, index) in todoList'>
                <span>[[ todo.name ]]:: [[ todo.todo ]]</span>
                <button type="button" class="removeBtn" v-on:click="remove_todo(todo, index)">x</button>
            </li>
        </ul>
    </div>
{% endblock content %}

{% block extra-script %}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'


        var vm = new Vue({
            delimiters: ['[[', ']]'], // (vue) 머스타치 문법에서 중괄호 한 번만 사용하겠다는 뜻
            el:'#app',
            data:{
                name: '',
                todo: '',
                todoList: [],
            },
            // Life cycle hook : created
            // Vue 인스턴스가 생성되는 시점에 실행되는 함수를 정의
            created: function() {
                console.log('created()...');
                // 직접 axios.get()을 정의해도 되지만, 일반적으로는 메소드 호출을 이용
                this.fetch_all_todo();
            },
            methods:{
                fetch_all_todo: function() {
                    console.log('fetch_all_todo()...');

                    // 자바스크립트의  'this'는 위치에 따라서 의미가 달라지므로 유의해야 한다.
                    // 일반적으로 Vue 인스턴스 내에서의 this는 해당 Vue 인스턴스를 의미한다.
                    // 그러나 axios.get() 구문 내에서 콜백함수 내에 정의된 this는 window 객체를 의미한다.
                    // 이를 해결하는 방법으로 '화살표 함수'를 이용할 수 있지만, 로컬 변수에 임시로 this(vue 인스턴스)를 저장해뒀다가 사용할 수도 있다.
                    var vm = this;

                    axios.get('/api/todo/list')
                    .then(function(res) {
                        console.log('GET RES', res);
                        vm.todoList = res.data; // 여기서 this는 window 객체를 의미한다.
                    })
                    .catch(function(err) {
                        console.log('GET ERR', err);
                    })
                },
                add_todo: function() {
                    console.log("add_todo()...");
                    if (this.todo === '') return;
                    if (this.name === '') this.name = '홍길동';
                    
                    // key 값은 db 테이블의 컬럼명과 일치해야 한다.
                    var postData = {
                        name: this.name,
                        todo: this.todo
                    }
                    var vm = this
                    axios.post('/api/todo/create/', postData)
                        .then(function(res) {
                            console.log("POST RES", res)
                            vm.todoList.push({id: res.data.id, name: res.data.name, todo: res.data.todo})
                        })
                        .catch(function(err) {
                            console.log("POST ERR", err)

                        })
                    this.name = this.todo = '';
                },
                remove_todo: function(todo, index) {
                    console.log("remove_todo()...", index);
                    if (confirm("Really Delete ?") === false) return;
                    
                    var vm = this
                    axios.delete('/api/todo/' + todo.id + '/delete/')
                        .then(function(res) {
                            console.log("DELETE RES", res);
                            vm.todoList.splice(index, 1);
                        })
                        .catch(function(err){
                            console.log("DELETE RES", err);
                        })
                },
            },
        })
    </script>
{% endblock extra-script %}